name: Velog Web build workdflow

on:
  pull_request:
    branches: ['main', 'development', 'hotfix']
    paths:
      - 'packages/velog-web/**'
      - '.github/workflows/velog-web-build.yml'

jobs:
  web-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.18.2s]
    defaults:
      run:
        working-directory: './packages/velog-web'

    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3.7.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile

      - name: add env
        run: pnpm ssm pull -e stage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: env copy
        run: pnpm env:copy -e stage

      - name: Build
        run: pnpm build
